website:
  title: "Beatriz e Julio"
  navbar:
    left:
      - href: galeria.qmd
      - href: mural-mensagens.qmd
      - href: lista-de-presentes.qmd
      - href: confirmar-presenca.qmd
      
        
        
        
lang: pt        