project:
  type: website
  post-render: _post-render.R
  preview: 
    port: 4200  

        
profile:
  default: portugues
  group: 
    - [portugues,english]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true