lang: pt        

project:
  title: "Beatriz e Julio"
  type: website
  output-dir: docs
    
website:
  navbar:
    left:
      - text: "Cerimônia"
        href: cerimonia.qmd
      - text: "Dicas"
        href: dicas.qmd             
      - text: "Confirmar presença"
        href: confirmar-presenca.qmd
      - text: "Galeria de fotos"
        href: galeria.qmd
      - text: "Mural de mensagens"
        href: mural-mensagens.qmd
      - text: "Lista de presentes"
        href: presentes.qmd
      - text: "Equipe"
        href: equipe.qmd        
    right: 
      - href: https://beaeju.com.br/index.html
        text: Português
      - href: https://beaeju.com.br/en/index.html
        text: English