website:
  title: "Beatriz e Julio"
  navbar:
    left:
      - href: cerimonia.qmd    
      - href: galeria.qmd
      - href: mural-mensagens.qmd
      - href: presentes.qmd
#      - href: confirmar-presenca.qmd
      
        
        
        
lang: pt        