lang: en

project:
  title: "Beatriz & Julio"
  type: website
  output-dir: docs/en

website:
  navbar:
    left:
      - text: "Celebration and Wedding party"
        href: celebracao.qmd
      - text: "Tips"
        href: dicas.qmd        
      # - text: "Confirmar presença"
      #   href: confirmar-presenca.qmd
      - text: "Photos"
        href: galeria.qmd
      - text: "Message board"
        href: mural-mensagens.qmd
      - text: "Wedding gifts"
        href: presentes.qmd
      - text: "Videos"
        href: videos.qmd        
    right: 
      - href: https://beaeju.com.br/index.html
        text: Português
      - href: https://beaeju.com.br/en/index.html
        text: English