lang: en

project:
  title: "Beatriz & Julio"
  type: website
  output-dir: docs/en

website:
  navbar:
    left:
      - text: "Ceremony and Wedding party"
        href: cerimonia.qmd
      # - text: "Confirmar presença"
      #   href: confirmar-presenca.qmd
      - text: "Photos"
        href: galeria.qmd
      - text: "Message board"
        href: mural-mensagens.qmd
      - text: "Wedding gifts"
        href: presentes.qmd
    right: 
      - href: https://beaeju.com.br/index.html
        text: Português
      - href: https://beaeju.com.br/en/index.html
        text: English